# Generated by Django 3.1.3 on 2021-02-19 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='termek',
            name='ar',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
