# Generated by Django 3.1.3 on 2021-02-20 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_termek_ar'),
    ]

    operations = [
        migrations.AddField(
            model_name='kategoria',
            name='leiras',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kategoria',
            name='slug',
            field=models.SlugField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='termek',
            name='leiras',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='termek',
            name='slug',
            field=models.SlugField(default=0),
            preserve_default=False,
        ),
    ]
