# Generated by Django 3.1.3 on 2021-02-20 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210220_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kategoria',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='termek',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
