# Generated by Django 3.1.3 on 2021-02-20 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210221_0009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='termek',
            name='akcios_ar',
        ),
        migrations.RemoveField(
            model_name='termek',
            name='ujdonsag',
        ),
        migrations.AlterField(
            model_name='kategoria',
            name='leiras',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='termek',
            name='leiras',
            field=models.TextField(blank=True, null=True),
        ),
    ]
