# Generated by Django 3.1.3 on 2021-02-21 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210221_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='szin',
            name='image',
            field=models.ImageField(blank=True, default='placeholder.png', null=True, upload_to='images/'),
        ),
    ]
