# Generated by Django 3.1.3 on 2021-02-23 18:07

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210221_1336'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kepek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='placeholder.png', null=True, upload_to='images/')),
            ],
        ),
        migrations.AlterField(
            model_name='kategoria',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='main.kategoria'),
        ),
        migrations.AlterField(
            model_name='termek',
            name='image_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='termekimage', to='main.szin'),
        ),
    ]
