# Generated by Django 3.1.3 on 2021-02-23 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_kategoria_borito'),
    ]

    operations = [
        migrations.AddField(
            model_name='termek',
            name='sorrend',
            field=models.IntegerField(default=0, unique=True),
            preserve_default=False,
        ),
    ]
