# Generated by Django 3.1.3 on 2021-02-23 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20210223_2205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='termek',
            name='sorrend',
        ),
    ]
