# Generated by Django 3.1.3 on 2021-02-23 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_termek_sorrend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='termek',
            name='sorrend',
        ),
    ]
