# Generated by Django 3.1.3 on 2021-02-23 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_termek_sorrend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termek',
            name='image_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='termekimage', to='main.szin'),
        ),
    ]
