# Generated by Django 3.1.3 on 2021-02-23 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_remove_termek_sorrend'),
    ]

    operations = [
        migrations.AddField(
            model_name='termek',
            name='sorrend',
            field=models.IntegerField(default=''),
        ),
    ]
