# Generated by Django 3.1.3 on 2021-02-23 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20210223_2226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='termek',
            name='sorrend',
        ),
    ]
