# Generated by Django 3.1.3 on 2021-02-23 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_auto_20210223_2247'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='termek',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='termek',
            name='sorrend',
        ),
    ]
