# Generated by Django 3.1.3 on 2021-02-23 21:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_auto_20210223_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='termek',
            name='sorrend',
            field=models.IntegerField(default=django.utils.timezone.now, unique=True),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='termek',
            unique_together={('sorrend', 'nev')},
        ),
    ]
