# Generated by Django 3.1.3 on 2021-08-04 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_auto_20210223_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kategoria',
            name='borito',
            field=models.ImageField(blank=True, default='images/placeholder.png', null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='kategoria',
            name='image',
            field=models.ImageField(blank=True, default='images/placeholder.png', null=True, upload_to='images'),
        ),
    ]
