# Generated by Django 3.1.3 on 2021-08-04 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_auto_20210804_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='szin',
            name='image',
            field=models.ImageField(blank=True, default='images/placeholder.png', null=True, upload_to='images/'),
        ),
    ]
