# Generated by Django 3.1.3 on 2021-08-04 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_auto_20210804_1115'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nev', models.CharField(max_length=255)),
                ('hex', models.CharField(max_length=7)),
            ],
        ),
        migrations.RemoveField(
            model_name='szin',
            name='hex',
        ),
        migrations.RemoveField(
            model_name='szin',
            name='nev',
        ),
        migrations.AddField(
            model_name='szin',
            name='szin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.color'),
        ),
    ]
