# Generated by Django 3.1.3 on 2021-08-05 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_meret_sorrend'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meret',
            options={'ordering': ['sorrend']},
        ),
        migrations.AddField(
            model_name='color',
            name='azonosito',
            field=models.IntegerField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='color',
            name='azonosito_szin',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
    ]
