# Generated by Django 3.1.3 on 2021-08-05 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_auto_20210805_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='azonosito',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
