# Generated by Django 3.1.3 on 2021-08-09 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_auto_20210809_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='small_image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='images/'),
        ),
    ]
