# Generated by Django 3.2.6 on 2021-08-12 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_kategoria_ar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='images/placeholder.jpg', null=True, upload_to='images/')),
                ('order', models.IntegerField()),
            ],
        ),
    ]
