# Generated by Django 3.2.6 on 2021-08-13 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_carousel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carousel',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='carousel',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
