# Generated by Django 3.2.6 on 2021-08-13 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_auto_20210813_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='name',
            field=models.CharField(default='Slider name', max_length=255),
        ),
    ]
